### ISSUE TITLE
The localization file size cannot exceed 30 Kb.

### ISSUE THREAD

**Issue by Kipyatochkov** [PavelZinchenko/EventHorizon-Issues#10]
In mods, localization that file size exceeds 30 Kb does not work.

**Comment by PavelZinchenko** [comment]
Can't reproduce the bug. Could you please provide a mod in which localization doesn't work?

**Comment by Kipyatochkov** [comment]
I sent you an email in February and March a mod with a database. Localization works in the database, but not in mod.

**Comment by PavelZinchenko** [comment]
found it

**Comment by PavelZinchenko** [comment]
Fixed. Download the latest database editor and build the mod again.
