### ISSUE TITLE
Database issue: don't work quest node types "CancelQuest" and "StartQuest"

### ISSUE THREAD

**Issue by Kipyatochkov** [PavelZinchenko/EventHorizon-Issues#11]
The quest stops, but continues to "work" when it comes to these types. "StartQuest" doesn't start an additional quest.

**Comment by PavelZinchenko** [comment]
StartQuest only works if the other quest has "Manual" activation type
CancelQuest is fixed - https://github.com/PavelZinchenko/EventHorizon/commit/fa008dc59ad14adae12bcb7aa0b78b5ca33283f5
