### ISSUE TITLE
Free component unlocking

### ISSUE THREAD

**Issue by PavelZinchenko** [PavelZinchenko/EventHorizon-Issues#2]
Click the unlock button on one locked component, and then click on another locked component before the conversation box pops up. You can unlock any component can't be unlocked like vanprick ray or unlock components with less money.

_Originally posted by @What566 in https://github.com/PavelZinchenko/EventHorizon-Editor/issues/2#issuecomment-591173280_

**Comment by PavelZinchenko** [comment]
> The way to unlock a compoent can't be unlocked
> 1.choose another compoent and click the unlock button
> 2.click the compoent you want to unlock as soon as you can (before the communicate box popping up,and you will find the icon will changed )
> 3.click the unlock button
> Then this compoent is unlocked

**Comment by PavelZinchenko** [comment]
fixed - https://github.com/PavelZinchenko/EventHorizon/commit/bef858362be93eb6c5632c13bbd67808c4d56642

**Comment by PavelZinchenko** [comment]
fixed - https://github.com/PavelZinchenko/EventHorizon/commit/bef858362be93eb6c5632c13bbd67808c4d56642

**Comment by What566** [comment]
look

**Comment by What566** [comment]
Why can't I upload my video?
